before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/scut/scut.go
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: kpurdon
    name: scut
  prerelease: auto
brew:
  github:
    owner: kpurdon
    name: scut
  commit_author:
    name: Kyle Purdon
    email: kylepurdon+scut@gmail.com
  homepage: "https://github.com/kpurdon/scut"
  description: "Tail for RabbitMQ."
